###

GET http://localhost:3000/healthcheck

###

POST http://localhost:3000/inventory/my
Content-Type: application/json

{
  "bot_id": 0,
  "gameID": 730
}

###

POST http://localhost:3000/inventory/their
Content-Type: application/json

{
  "bot_id": 0,
  "gameID": 730,
  "steam_id": "<steam_id>"
}

###

POST http://localhost:3000/inventory/check
Content-Type: application/json

{
  "bot_id": 0,
  "gameID": 730,
  "asset_ids": [],
  "steam_id": "<steam_id>"
}

###

POST http://localhost:3000/inventory/getcsgoitemsinfo
Content-Type: application/json

{
  "bot_id": 0,
  "links": []
}

###

POST http://localhost:3000/tradeoffer/sendgive
Content-Type: application/json

{
  "bot_id": 0,
  "trade_url": "",
  "comment": "",
  "items": []
}

###
