export enum EBotEvents {
  ERROR = 'error',
  LOGIN = 'login',
  LIMIT = 'limit',
  DISCONNECT = 'disconnect',
  STEAM_GUARD = 'steamGuard',
  SET_COOKIES = 'setCookies',
  CONFIRMATIONS = 'confirmations',
  HEALTHCHECK = 'healthcheck',
  NEW_OFFER = 'newOffer',
  OFFER_DECLINED = 'offerDeclined',
  SEND_OFFER_STATE = 'sendOfferState',
  SEND_OFFER_ITEMS = 'sendOfferItems',
  GC_CONNECTED = 'gcConnected',
  PLAYING_STATE = 'playingState',
  USER = 'user',
}
